/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pokemonbattle;

import java.applet.Applet;
import java.applet.AudioClip;
import java.net.*;
public class BattleUI extends javax.swing.JFrame
{
    public int turnos_total;
    public int turno;
    public boolean Solar_on = false;
    public int cuenta;
    String hit_points, total;
    int HP, total2;
    int randomnum;
    int porcentaje;
    boolean show = true;
    boolean hide = true;
    AudioClip clip, clip2, clip3;
    
    public BattleUI()
    {
        initComponents();
        HideArrows();
        Ivy_items_panel.setVisible(false);
        Char_items_panel.setVisible(false);
        IvyHideButtons();
        Again_button.setVisible(false);
        try
        {
          clip = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/PokemonWild - KantoTheme.wav"));
          clip.loop();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        CharmeleonImage_label = new javax.swing.JLabel();
        IvysaurImage_label = new javax.swing.JLabel();
        CharmeleonHP_panel = new javax.swing.JPanel();
        Charmeleon_label = new javax.swing.JLabel();
        CharmeleonHP_bar = new javax.swing.JProgressBar();
        CharmeleonHP_label = new javax.swing.JLabel();
        CharmeleonLvl_label = new javax.swing.JLabel();
        CharmeleonHitpoints_label = new javax.swing.JLabel();
        CharmeleonSlash_label = new javax.swing.JLabel();
        IvysaurHp_panel = new javax.swing.JPanel();
        Ivysaur_label = new javax.swing.JLabel();
        IvysaurHP_bar = new javax.swing.JProgressBar();
        IvysaurHP_label = new javax.swing.JLabel();
        IvysaurLvl_label = new javax.swing.JLabel();
        IvysaurHitpoints_label = new javax.swing.JLabel();
        IvysaurSlash_label = new javax.swing.JLabel();
        Flamethrower_button = new javax.swing.JLabel();
        Firespin_button = new javax.swing.JLabel();
        Slash_button = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tackle_button = new javax.swing.JLabel();
        VineWhip_button = new javax.swing.JLabel();
        RazorLeaf_button = new javax.swing.JLabel();
        SolarBeam_button = new javax.swing.JLabel();
        Ember_button = new javax.swing.JLabel();
        Ivysaur_arrow1 = new javax.swing.JLabel();
        Ivysaur_arrow4 = new javax.swing.JLabel();
        Ivysaur_arrow2 = new javax.swing.JLabel();
        Charmeleon_arrow4 = new javax.swing.JLabel();
        Ivysaur_arrow3 = new javax.swing.JLabel();
        Charmeleon_arrow2 = new javax.swing.JLabel();
        Charmeleon_arrow1 = new javax.swing.JLabel();
        Charmeleon_arrow3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BattleLog_txtarea = new javax.swing.JTextArea();
        IvyItems_button = new javax.swing.JLabel();
        Ivy_items_panel = new javax.swing.JPanel();
        IvyPotions_label = new javax.swing.JLabel();
        Ivy_potion_number = new javax.swing.JLabel();
        CharItems_button = new javax.swing.JLabel();
        Char_items_panel = new javax.swing.JPanel();
        CharPotions_label = new javax.swing.JLabel();
        Char_potion_number = new javax.swing.JLabel();
        Again_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Battle *BETA*");
        getContentPane().setLayout(null);

        CharmeleonImage_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Charmeleon2.png"))); // NOI18N
        getContentPane().add(CharmeleonImage_label);
        CharmeleonImage_label.setBounds(1080, 0, 352, 409);

        IvysaurImage_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ivysaur2.png"))); // NOI18N
        getContentPane().add(IvysaurImage_label);
        IvysaurImage_label.setBounds(10, 0, 375, 384);

        CharmeleonHP_panel.setBackground(new java.awt.Color(204, 204, 204));
        CharmeleonHP_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 4, true));

        Charmeleon_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Charmeleon_label.setText("Charmeleon");

        CharmeleonHP_bar.setValue(100);
        CharmeleonHP_bar.setString("100");

        CharmeleonHP_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CharmeleonHP_label.setForeground(new java.awt.Color(204, 153, 0));
        CharmeleonHP_label.setText("HP");

        CharmeleonLvl_label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CharmeleonLvl_label.setText("Lv100");

        CharmeleonHitpoints_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CharmeleonHitpoints_label.setText("324");

        CharmeleonSlash_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CharmeleonSlash_label.setText("/ 324");

        javax.swing.GroupLayout CharmeleonHP_panelLayout = new javax.swing.GroupLayout(CharmeleonHP_panel);
        CharmeleonHP_panel.setLayout(CharmeleonHP_panelLayout);
        CharmeleonHP_panelLayout.setHorizontalGroup(
            CharmeleonHP_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CharmeleonHP_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CharmeleonHP_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CharmeleonHP_panelLayout.createSequentialGroup()
                        .addComponent(CharmeleonHP_label)
                        .addGap(14, 14, 14)
                        .addComponent(CharmeleonHP_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CharmeleonHP_panelLayout.createSequentialGroup()
                        .addComponent(Charmeleon_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CharmeleonLvl_label)
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CharmeleonHP_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CharmeleonHitpoints_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CharmeleonSlash_label)
                .addGap(24, 24, 24))
        );
        CharmeleonHP_panelLayout.setVerticalGroup(
            CharmeleonHP_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CharmeleonHP_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CharmeleonHP_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Charmeleon_label)
                    .addComponent(CharmeleonLvl_label))
                .addGap(12, 12, 12)
                .addGroup(CharmeleonHP_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CharmeleonHP_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CharmeleonHP_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CharmeleonHP_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CharmeleonHitpoints_label)
                    .addComponent(CharmeleonSlash_label))
                .addContainerGap())
        );

        getContentPane().add(CharmeleonHP_panel);
        CharmeleonHP_panel.setBounds(1169, 438, 255, 103);

        IvysaurHp_panel.setBackground(new java.awt.Color(204, 204, 204));
        IvysaurHp_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 4, true));

        Ivysaur_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ivysaur_label.setText("IVYSAUR");

        IvysaurHP_bar.setValue(100);

        IvysaurHP_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IvysaurHP_label.setForeground(new java.awt.Color(204, 153, 0));
        IvysaurHP_label.setText("HP");

        IvysaurLvl_label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        IvysaurLvl_label.setText("Lv100");

        IvysaurHitpoints_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        IvysaurHitpoints_label.setText("324");

        IvysaurSlash_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        IvysaurSlash_label.setText("/ 324");

        javax.swing.GroupLayout IvysaurHp_panelLayout = new javax.swing.GroupLayout(IvysaurHp_panel);
        IvysaurHp_panel.setLayout(IvysaurHp_panelLayout);
        IvysaurHp_panelLayout.setHorizontalGroup(
            IvysaurHp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IvysaurHp_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IvysaurHp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IvysaurHp_panelLayout.createSequentialGroup()
                        .addComponent(IvysaurHP_label)
                        .addGap(14, 14, 14)
                        .addComponent(IvysaurHP_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(IvysaurHp_panelLayout.createSequentialGroup()
                        .addComponent(Ivysaur_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IvysaurLvl_label)
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IvysaurHp_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IvysaurHitpoints_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IvysaurSlash_label)
                .addGap(24, 24, 24))
        );
        IvysaurHp_panelLayout.setVerticalGroup(
            IvysaurHp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IvysaurHp_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IvysaurHp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ivysaur_label)
                    .addComponent(IvysaurLvl_label))
                .addGap(12, 12, 12)
                .addGroup(IvysaurHp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IvysaurHP_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IvysaurHP_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(IvysaurHp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IvysaurHitpoints_label)
                    .addComponent(IvysaurSlash_label))
                .addContainerGap())
        );

        getContentPane().add(IvysaurHp_panel);
        IvysaurHp_panel.setBounds(10, 427, 255, 103);

        Flamethrower_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flamethrower_button.png"))); // NOI18N
        Flamethrower_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Flamethrower_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                Flamethrower_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                Flamethrower_buttonMouseExited(evt);
            }
        });
        getContentPane().add(Flamethrower_button);
        Flamethrower_button.setBounds(1296, 556, 132, 39);

        Firespin_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FireSpin_button.png"))); // NOI18N
        Firespin_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Firespin_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                Firespin_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                Firespin_buttonMouseExited(evt);
            }
        });
        getContentPane().add(Firespin_button);
        Firespin_button.setBounds(1134, 556, 125, 39);

        Slash_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Slash_button.png"))); // NOI18N
        Slash_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Slash_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                Slash_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                Slash_buttonMouseExited(evt);
            }
        });
        getContentPane().add(Slash_button);
        Slash_button.setBounds(1134, 623, 125, 29);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1156, 663, 0, 0);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 556, 0, 0);

        Tackle_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tackle_button.png"))); // NOI18N
        Tackle_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Tackle_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                Tackle_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                Tackle_buttonMouseExited(evt);
            }
        });
        getContentPane().add(Tackle_button);
        Tackle_button.setBounds(34, 556, 125, 29);

        VineWhip_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VineWhip_button.png"))); // NOI18N
        VineWhip_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                VineWhip_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                VineWhip_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                VineWhip_buttonMouseExited(evt);
            }
        });
        getContentPane().add(VineWhip_button);
        VineWhip_button.setBounds(193, 558, 124, 27);

        RazorLeaf_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RazorLeaf_button.png"))); // NOI18N
        RazorLeaf_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                RazorLeaf_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                RazorLeaf_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                RazorLeaf_buttonMouseExited(evt);
            }
        });
        getContentPane().add(RazorLeaf_button);
        RazorLeaf_button.setBounds(34, 613, 126, 29);

        SolarBeam_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SolarBeam_button.png"))); // NOI18N
        SolarBeam_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                SolarBeam_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                SolarBeam_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                SolarBeam_buttonMouseExited(evt);
            }
        });
        getContentPane().add(SolarBeam_button);
        SolarBeam_button.setBounds(193, 613, 125, 29);

        Ember_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ember_button.png"))); // NOI18N
        Ember_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Ember_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                Ember_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                Ember_buttonMouseExited(evt);
            }
        });
        getContentPane().add(Ember_button);
        Ember_button.setBounds(1296, 623, 125, 29);

        Ivysaur_arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow_button.png"))); // NOI18N
        getContentPane().add(Ivysaur_arrow1);
        Ivysaur_arrow1.setBounds(10, 571, 7, 14);

        Ivysaur_arrow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow_button.png"))); // NOI18N
        getContentPane().add(Ivysaur_arrow4);
        Ivysaur_arrow4.setBounds(176, 628, 7, 14);

        Ivysaur_arrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow_button.png"))); // NOI18N
        getContentPane().add(Ivysaur_arrow2);
        Ivysaur_arrow2.setBounds(10, 628, 7, 14);

        Charmeleon_arrow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow_button.png"))); // NOI18N
        getContentPane().add(Charmeleon_arrow4);
        Charmeleon_arrow4.setBounds(1283, 638, 7, 14);

        Ivysaur_arrow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow_button.png"))); // NOI18N
        getContentPane().add(Ivysaur_arrow3);
        Ivysaur_arrow3.setBounds(176, 571, 7, 14);

        Charmeleon_arrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow_button.png"))); // NOI18N
        getContentPane().add(Charmeleon_arrow2);
        Charmeleon_arrow2.setBounds(1283, 572, 7, 14);

        Charmeleon_arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow_button.png"))); // NOI18N
        getContentPane().add(Charmeleon_arrow1);
        Charmeleon_arrow1.setBounds(1121, 566, 7, 14);

        Charmeleon_arrow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow_button.png"))); // NOI18N
        getContentPane().add(Charmeleon_arrow3);
        Charmeleon_arrow3.setBounds(1121, 638, 7, 14);

        BattleLog_txtarea.setColumns(20);
        BattleLog_txtarea.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BattleLog_txtarea.setRows(5);
        BattleLog_txtarea.setEnabled(false);
        jScrollPane1.setViewportView(BattleLog_txtarea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 92, 570, 328);

        IvyItems_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Items_button.png"))); // NOI18N
        IvyItems_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                IvyItems_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(IvyItems_button);
        IvyItems_button.setBounds(30, 670, 124, 27);

        Ivy_items_panel.setBackground(new java.awt.Color(255, 255, 255));
        Ivy_items_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Ivy_items_panel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                Ivy_items_panelMouseExited(evt);
            }
        });

        IvyPotions_label.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        IvyPotions_label.setText("Potions");
        IvyPotions_label.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                IvyPotions_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                IvyPotions_labelMouseEntered(evt);
            }
        });

        Ivy_potion_number.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Ivy_potion_number.setText("6");

        javax.swing.GroupLayout Ivy_items_panelLayout = new javax.swing.GroupLayout(Ivy_items_panel);
        Ivy_items_panel.setLayout(Ivy_items_panelLayout);
        Ivy_items_panelLayout.setHorizontalGroup(
            Ivy_items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ivy_items_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IvyPotions_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ivy_potion_number)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Ivy_items_panelLayout.setVerticalGroup(
            Ivy_items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ivy_items_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Ivy_items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IvyPotions_label)
                    .addComponent(Ivy_potion_number))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(Ivy_items_panel);
        Ivy_items_panel.setBounds(336, 531, 104, 55);

        CharItems_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Items_button.png"))); // NOI18N
        CharItems_button.setToolTipText("");
        CharItems_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                CharItems_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(CharItems_button);
        CharItems_button.setBounds(1300, 670, 124, 27);

        Char_items_panel.setBackground(new java.awt.Color(255, 255, 255));
        Char_items_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Char_items_panel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                Char_items_panelMouseExited(evt);
            }
        });

        CharPotions_label.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CharPotions_label.setText("Potions");
        CharPotions_label.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                CharPotions_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                CharPotions_labelMouseEntered(evt);
            }
        });

        Char_potion_number.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Char_potion_number.setText("6");

        javax.swing.GroupLayout Char_items_panelLayout = new javax.swing.GroupLayout(Char_items_panel);
        Char_items_panel.setLayout(Char_items_panelLayout);
        Char_items_panelLayout.setHorizontalGroup(
            Char_items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Char_items_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CharPotions_label)
                .addGap(18, 18, 18)
                .addComponent(Char_potion_number)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Char_items_panelLayout.setVerticalGroup(
            Char_items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Char_items_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Char_items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CharPotions_label)
                    .addComponent(Char_potion_number))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(Char_items_panel);
        Char_items_panel.setBounds(980, 540, 102, 51);

        Again_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Again_button.setText("PLAY AGAIN!");
        Again_button.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Again_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(Again_button);
        Again_button.setBounds(650, 620, 180, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1470, 710);

        setSize(new java.awt.Dimension(1491, 753));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tackle_buttonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Tackle_buttonMouseEntered
    {//GEN-HEADEREND:event_Tackle_buttonMouseEntered
//        try
//        {
//          clip = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
//          clip.play();
//        }
//        
//        catch(MalformedURLException e)
//        {
//            System.out.print(e);
//        }
        
        Ivysaur_arrow1.setVisible(true);
    }//GEN-LAST:event_Tackle_buttonMouseEntered

    private void Tackle_buttonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Tackle_buttonMouseExited
    {//GEN-HEADEREND:event_Tackle_buttonMouseExited
        Ivysaur_arrow1.setVisible(false);
    }//GEN-LAST:event_Tackle_buttonMouseExited

    private void RazorLeaf_buttonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RazorLeaf_buttonMouseEntered
    {//GEN-HEADEREND:event_RazorLeaf_buttonMouseEntered
        /*try
        {
          AudioClip clip = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
          clip.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }*/
        
        Ivysaur_arrow2.setVisible(true);
    }//GEN-LAST:event_RazorLeaf_buttonMouseEntered

    private void RazorLeaf_buttonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RazorLeaf_buttonMouseExited
    {//GEN-HEADEREND:event_RazorLeaf_buttonMouseExited
        Ivysaur_arrow2.setVisible(false);
    }//GEN-LAST:event_RazorLeaf_buttonMouseExited

    private void VineWhip_buttonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_VineWhip_buttonMouseEntered
    {//GEN-HEADEREND:event_VineWhip_buttonMouseEntered
        /*try
        {
          AudioClip clip = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
          clip.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }*/
        
        Ivysaur_arrow3.setVisible(true);
    }//GEN-LAST:event_VineWhip_buttonMouseEntered

    private void VineWhip_buttonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_VineWhip_buttonMouseExited
    {//GEN-HEADEREND:event_VineWhip_buttonMouseExited
        Ivysaur_arrow3.setVisible(false);
    }//GEN-LAST:event_VineWhip_buttonMouseExited

    private void SolarBeam_buttonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SolarBeam_buttonMouseEntered
    {//GEN-HEADEREND:event_SolarBeam_buttonMouseEntered
        /*try
        {
          AudioClip clip = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
          clip.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }*/
        
        Ivysaur_arrow4.setVisible(true);
    }//GEN-LAST:event_SolarBeam_buttonMouseEntered

    private void SolarBeam_buttonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SolarBeam_buttonMouseExited
    {//GEN-HEADEREND:event_SolarBeam_buttonMouseExited
        Ivysaur_arrow4.setVisible(false);
    }//GEN-LAST:event_SolarBeam_buttonMouseExited

    private void Firespin_buttonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Firespin_buttonMouseEntered
    {//GEN-HEADEREND:event_Firespin_buttonMouseEntered
        /*try
        {
          AudioClip clip = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
          clip.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }*/
        
        Charmeleon_arrow1.setVisible(true);
    }//GEN-LAST:event_Firespin_buttonMouseEntered

    private void Firespin_buttonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Firespin_buttonMouseExited
    {//GEN-HEADEREND:event_Firespin_buttonMouseExited
        Charmeleon_arrow1.setVisible(false);
    }//GEN-LAST:event_Firespin_buttonMouseExited

    private void Slash_buttonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Slash_buttonMouseEntered
    {//GEN-HEADEREND:event_Slash_buttonMouseEntered
        /*try
        {
          AudioClip clip = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
          clip.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }*/
        
        Charmeleon_arrow3.setVisible(true);
    }//GEN-LAST:event_Slash_buttonMouseEntered

    private void Slash_buttonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Slash_buttonMouseExited
    {//GEN-HEADEREND:event_Slash_buttonMouseExited
        Charmeleon_arrow3.setVisible(false);
    }//GEN-LAST:event_Slash_buttonMouseExited

    private void Flamethrower_buttonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Flamethrower_buttonMouseEntered
    {//GEN-HEADEREND:event_Flamethrower_buttonMouseEntered
        /*try
        {
          AudioClip clip = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
          clip.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }*/
        
        Charmeleon_arrow2.setVisible(true);
    }//GEN-LAST:event_Flamethrower_buttonMouseEntered

    private void Flamethrower_buttonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Flamethrower_buttonMouseExited
    {//GEN-HEADEREND:event_Flamethrower_buttonMouseExited
        Charmeleon_arrow2.setVisible(false);
    }//GEN-LAST:event_Flamethrower_buttonMouseExited

    private void Ember_buttonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Ember_buttonMouseEntered
    {//GEN-HEADEREND:event_Ember_buttonMouseEntered
        /*try
        {
          AudioClip clip = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
          clip.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }*/
        Charmeleon_arrow4.setVisible(true);
    }//GEN-LAST:event_Ember_buttonMouseEntered

    private void Ember_buttonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Ember_buttonMouseExited
    {//GEN-HEADEREND:event_Ember_buttonMouseExited
        Charmeleon_arrow4.setVisible(false);
    }//GEN-LAST:event_Ember_buttonMouseExited

    private void Tackle_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Tackle_buttonMouseClicked
    {//GEN-HEADEREND:event_Tackle_buttonMouseClicked
        
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        hit_points = CharmeleonHitpoints_label.getText();
        HP = Integer.parseInt(hit_points);
        randomnum = (int)(Math.random()*(56-50) + 50);
        HP-= randomnum;
        if(HP <= 0)
        {
            HP = 0;
            IvyHideButtons();
            CharHideButtons();
            hide = false;
            show = false;
            BattleLog_txtarea.append("Game Over!\n");
            BattleLog_txtarea.append("IVYSAUR is the WINER!\n");
            BattleLog_txtarea.append("Click the button below to play again!");
            Again_button.setVisible(true);
            clip.stop();
            try
            {
              clip3 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/108-victory-vs-wild-pokemon-.wav"));
              clip3.loop();
            }
            
            catch(MalformedURLException e)
            {
                System.out.print(e);
            }
        }
        CharmeleonHitpoints_label.setText("" + HP);
        porcentaje = (HP * 100) / 324;
        CharmeleonHP_bar.setValue(porcentaje);
        BattleLog_txtarea.append("IVYSAUR used TACKLE!\n");
        turnos_total++;
        CharShowButtons();
        IvyHideButtons();
    }//GEN-LAST:event_Tackle_buttonMouseClicked

    private void RazorLeaf_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RazorLeaf_buttonMouseClicked
    {//GEN-HEADEREND:event_RazorLeaf_buttonMouseClicked
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        hit_points = CharmeleonHitpoints_label.getText();
        HP = Integer.parseInt(hit_points);
        randomnum = (int)Math.floor(Math.random()*(56-50) + 50);
        HP-= randomnum;
        if(HP <= 0)
        {
            HP = 0;
            IvyHideButtons();
            CharHideButtons();
            hide = false;
            show = false;
            BattleLog_txtarea.append("Game Over!\n");
            BattleLog_txtarea.append("IVYSAUR is the WINER!\n");
            BattleLog_txtarea.append("Click the button below to play again!");
            Again_button.setVisible(true);
            clip.stop();
            try
            {
              clip3 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/108-victory-vs-wild-pokemon-.wav"));
              clip3.loop();
            }
            
            catch(MalformedURLException e)
            {
                System.out.print(e);
            }
        }
        CharmeleonHitpoints_label.setText("" + HP);
        porcentaje = (HP * 100) / 324;
        CharmeleonHP_bar.setValue(porcentaje);
        BattleLog_txtarea.append("IVYSAUR used RAZOR LEAF!\n");
        turnos_total++;
        CharShowButtons();
        IvyHideButtons();
    }//GEN-LAST:event_RazorLeaf_buttonMouseClicked

    private void VineWhip_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_VineWhip_buttonMouseClicked
    {//GEN-HEADEREND:event_VineWhip_buttonMouseClicked
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        hit_points = CharmeleonHitpoints_label.getText();
        HP = Integer.parseInt(hit_points);
        randomnum = (int)Math.floor(Math.random()*(46-40) + 40);
        HP-= randomnum;
        if(HP <= 0)
        {
            HP = 0;
            IvyHideButtons();
            CharHideButtons();
            hide = false;
            show = false;
            BattleLog_txtarea.append("Game Over!\n");
            BattleLog_txtarea.append("IVYSAUR is the WINER!\n");
            BattleLog_txtarea.append("Click the button below to play again!");
            Again_button.setVisible(true);
            clip.stop();
            try
            {
              clip3 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/108-victory-vs-wild-pokemon-.wav"));
              clip3.loop();
            }
            
            catch(MalformedURLException e)
            {
                System.out.print(e);
            }
        }
        CharmeleonHitpoints_label.setText("" + HP);
        porcentaje = (HP * 100) / 324;
        CharmeleonHP_bar.setValue(porcentaje);
        BattleLog_txtarea.append("IVYSAUR used VINE WHIP!\n");
        turnos_total++;
        CharShowButtons();
        IvyHideButtons();
    }//GEN-LAST:event_VineWhip_buttonMouseClicked

    private void SolarBeam_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SolarBeam_buttonMouseClicked
    {//GEN-HEADEREND:event_SolarBeam_buttonMouseClicked
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        if(Solar_on == false)
        {
            BattleLog_txtarea.append("Ivysaur is gathering energy....\n");
            cuenta = turnos_total + 2;
            Solar_on = true;
            turnos_total++;
            CharShowButtons();
            IvyHideButtons();
        }
        
        else if(Solar_on == true)
        {
            hit_points = CharmeleonHitpoints_label.getText();
            HP = Integer.parseInt(hit_points);
            HP-= 120;
            if(HP <= 0)
            {
                HP = 0;
                IvyHideButtons();
                CharHideButtons();
                hide = false;
                show = false;
                BattleLog_txtarea.append("Game Over!\n");
                BattleLog_txtarea.append("IVYSAUR is the WINER!\n");
                BattleLog_txtarea.append("Click the button below to play again!");
                Again_button.setVisible(true);
                clip.stop();
                try
            {
              clip3 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/108-victory-vs-wild-pokemon-.wav"));
              clip3.loop();
            }
            
            catch(MalformedURLException e)
            {
                System.out.print(e);
            }
            }
            
        CharmeleonHitpoints_label.setText("" + HP);
        porcentaje = (HP * 100) / 324;
        CharmeleonHP_bar.setValue(porcentaje);
        BattleLog_txtarea.append("IVYSAUR used SOLAR BEAM!\n");
        turnos_total++;
        Solar_on = false;
        cuenta = 0;
        CharShowButtons();
        IvyHideButtons();
        }
    }//GEN-LAST:event_SolarBeam_buttonMouseClicked

    private void Firespin_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Firespin_buttonMouseClicked
    {//GEN-HEADEREND:event_Firespin_buttonMouseClicked
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        hit_points = IvysaurHitpoints_label.getText();
        HP = Integer.parseInt(hit_points);
        randomnum = (int)Math.floor(Math.random()*(36-30) + 30);
        HP-= randomnum;
        if(HP <= 0)
        {
            HP = 0;
            IvyHideButtons();
            CharHideButtons();
            hide = false;
            show = false;
            BattleLog_txtarea.append("Game Over!\n");
            BattleLog_txtarea.append("CHARMELEON is the WINER!\n");
            BattleLog_txtarea.append("Click the button below to play again!");
            Again_button.setVisible(true);
            clip.stop();
            try
            {
              clip3 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/108-victory-vs-wild-pokemon-.wav"));
              clip3.loop();
            }
            
            catch(MalformedURLException e)
            {
                System.out.print(e);
            }
        }
        IvysaurHitpoints_label.setText("" + HP);
        porcentaje = (HP * 100) / 324;
        IvysaurHP_bar.setValue(porcentaje);
        BattleLog_txtarea.append("CHARMELEON used FIRE SPIN!\n");
        turnos_total++;
        IvyShowButtons();
        CharHideButtons();
        if(Solar_on == true)
        {
            if(turnos_total == cuenta)
            {
                Tackle_button.setVisible(false);
                RazorLeaf_button.setVisible(false);
                VineWhip_button.setVisible(false);
                SolarBeam_button.setVisible(true);
                BattleLog_txtarea.append("Ivysaur has gathered enough energy.\n");
            }
        }        
    }//GEN-LAST:event_Firespin_buttonMouseClicked

    private void Slash_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Slash_buttonMouseClicked
    {//GEN-HEADEREND:event_Slash_buttonMouseClicked
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        hit_points = IvysaurHitpoints_label.getText();
        HP = Integer.parseInt(hit_points);
        randomnum = (int)Math.floor(Math.random()*(70-65) + 65);
        HP-= randomnum;
        if(HP <= 0)
        {
            HP = 0;
            IvyHideButtons();
            CharHideButtons();
            hide = false;
            show = false;
            BattleLog_txtarea.append("Game Over!\n");
            BattleLog_txtarea.append("CHARMELEON is the WINER!\n");
            BattleLog_txtarea.append("Click the button below to play again!");
            Again_button.setVisible(true);
            clip.stop();
            try
            {
              clip3 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/108-victory-vs-wild-pokemon-.wav"));
              clip3.loop();
            }
            
            catch(MalformedURLException e)
            {
                System.out.print(e);
            }
        }
        IvysaurHitpoints_label.setText("" + HP);
        porcentaje = (HP * 100) / 324;
        IvysaurHP_bar.setValue(porcentaje);
        BattleLog_txtarea.append("CHARMELEON used SLASH!\n");
        turnos_total++;
        IvyShowButtons();
        CharHideButtons();
        if(Solar_on == true)
        {
            if(turnos_total == cuenta)
            {
                Tackle_button.setVisible(false);
                RazorLeaf_button.setVisible(false);
                VineWhip_button.setVisible(false);
                SolarBeam_button.setVisible(true);
                BattleLog_txtarea.append("Ivysaur has gathered enough energy.\n");
            }
        }
    }//GEN-LAST:event_Slash_buttonMouseClicked

    private void Flamethrower_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Flamethrower_buttonMouseClicked
    {//GEN-HEADEREND:event_Flamethrower_buttonMouseClicked
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        hit_points = IvysaurHitpoints_label.getText();
        HP = Integer.parseInt(hit_points);
        randomnum = (int)Math.floor(Math.random()*(90-85) + 85);
        HP-= randomnum;
        if(HP <= 0)
        {
            HP = 0;
            IvyHideButtons();
            CharHideButtons();
            hide = false;
            show = false;
            BattleLog_txtarea.append("Game Over!\n");
            BattleLog_txtarea.append("CHARMELEON is the WINER!\n");
            BattleLog_txtarea.append("Click the button below to play again!");
            Again_button.setVisible(true);
            clip.stop();
            try
            {
              clip3 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/108-victory-vs-wild-pokemon-.wav"));
              clip3.loop();
            }
            
            catch(MalformedURLException e)
            {
                System.out.print(e);
            }
        }
        IvysaurHitpoints_label.setText("" + HP);
        porcentaje = (HP * 100) / 324;
        IvysaurHP_bar.setValue(porcentaje);
        BattleLog_txtarea.append("CHARMELEON used FLAMETHROWER!\n It's supper effective!\n");
        turnos_total++;
        IvyShowButtons();
        CharHideButtons();
        if(Solar_on == true)
        {
            if(turnos_total == cuenta)
            {
                Tackle_button.setVisible(false);
                RazorLeaf_button.setVisible(false);
                VineWhip_button.setVisible(false);
                SolarBeam_button.setVisible(true);
                BattleLog_txtarea.append("Ivysaur has gathered enough energy.\n");
            }
        }
    }//GEN-LAST:event_Flamethrower_buttonMouseClicked

    private void Ember_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Ember_buttonMouseClicked
    {//GEN-HEADEREND:event_Ember_buttonMouseClicked
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        hit_points = IvysaurHitpoints_label.getText();
        HP = Integer.parseInt(hit_points);
        randomnum = (int)Math.floor(Math.random()*(40-35) + 35);
        HP-= randomnum;
        if(HP <= 0)
        {
            HP = 0;
            IvyHideButtons();
            CharHideButtons();
            hide = false;
            show = false;
            BattleLog_txtarea.append("Game Over!\n");
            BattleLog_txtarea.append("CHARMELEON is the WINER!\n");
            BattleLog_txtarea.append("Click the button below to play again!");
            Again_button.setVisible(true);
            clip.stop();
            try
            {
              clip3 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/108-victory-vs-wild-pokemon-.wav"));
              clip3.loop();
            }
            
            catch(MalformedURLException e)
            {
                System.out.print(e);
            }
        }
        IvysaurHitpoints_label.setText("" + HP);
        porcentaje = (HP * 100) / 324;
        IvysaurHP_bar.setValue(porcentaje);
        BattleLog_txtarea.append("CHARMELEON used EMBER!\n");
        turnos_total++;
        IvyShowButtons();
        CharHideButtons();
        if(Solar_on == true)
        {
            if(turnos_total == cuenta)
            {
                Tackle_button.setVisible(false);
                RazorLeaf_button.setVisible(false);
                VineWhip_button.setVisible(false);
                SolarBeam_button.setVisible(true);
                BattleLog_txtarea.append("Ivysaur has gathered enough energy.\n");
            }
        }
    }//GEN-LAST:event_Ember_buttonMouseClicked

    private void IvyPotions_labelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_IvyPotions_labelMouseClicked
    {//GEN-HEADEREND:event_IvyPotions_labelMouseClicked
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        hit_points = IvysaurHitpoints_label.getText();
        HP = Integer.parseInt(hit_points);
        total = Ivy_potion_number.getText();
        total2 = Integer.parseInt(total);
        if(total2 > 0 && HP < 324 && HP != 0)
        {
            HP+= 45;
            if(HP >= 324)
            {
                HP = 324;
            }
            IvysaurHitpoints_label.setText("" + HP);
            porcentaje = (HP * 100) / 324;
            IvysaurHP_bar.setValue(porcentaje);
            total2-= 1;
            Ivy_potion_number.setText("" + total2);
        }
        Ivy_items_panel.setVisible(false);
    }//GEN-LAST:event_IvyPotions_labelMouseClicked

    private void IvyItems_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_IvyItems_buttonMouseClicked
    {//GEN-HEADEREND:event_IvyItems_buttonMouseClicked
        Ivy_items_panel.setVisible(true);
    }//GEN-LAST:event_IvyItems_buttonMouseClicked

    private void CharPotions_labelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CharPotions_labelMouseClicked
    {//GEN-HEADEREND:event_CharPotions_labelMouseClicked
        try
        {
            clip2 = Applet.newAudioClip(new URL("file:/C:/Users/Alejandro/java/NetBeans/PokemonBattle/src/Button_sound.wav"));
            clip2.play();
        }
        
        catch(MalformedURLException e)
        {
            System.out.print(e);
        }
        
        hit_points = CharmeleonHitpoints_label.getText();
        HP = Integer.parseInt(hit_points);
        total = Char_potion_number.getText();
        total2 = Integer.parseInt(total);
        if(total2 > 0 && HP < 324)
        {
            HP+= 45;
            if(HP >= 324)
            {
                HP = 324;
            }
            CharmeleonHitpoints_label.setText("" + HP);
            porcentaje = (HP * 100) / 324;
            CharmeleonHP_bar.setValue(porcentaje);
            total2-= 1;
            Char_potion_number.setText("" + total2);
        }
        Char_items_panel.setVisible(false);
    }//GEN-LAST:event_CharPotions_labelMouseClicked

    private void CharItems_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CharItems_buttonMouseClicked
    {//GEN-HEADEREND:event_CharItems_buttonMouseClicked
        Char_items_panel.setVisible(true);
    }//GEN-LAST:event_CharItems_buttonMouseClicked

    private void Ivy_items_panelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Ivy_items_panelMouseExited
    {//GEN-HEADEREND:event_Ivy_items_panelMouseExited
        Ivy_items_panel.setVisible(false);
    }//GEN-LAST:event_Ivy_items_panelMouseExited

    private void IvyPotions_labelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_IvyPotions_labelMouseEntered
    {//GEN-HEADEREND:event_IvyPotions_labelMouseEntered
        Ivy_items_panel.setVisible(true);
    }//GEN-LAST:event_IvyPotions_labelMouseEntered

    private void Char_items_panelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Char_items_panelMouseExited
    {//GEN-HEADEREND:event_Char_items_panelMouseExited
        Char_items_panel.setVisible(false);
    }//GEN-LAST:event_Char_items_panelMouseExited

    private void CharPotions_labelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CharPotions_labelMouseEntered
    {//GEN-HEADEREND:event_CharPotions_labelMouseEntered
        Char_items_panel.setVisible(true);
    }//GEN-LAST:event_CharPotions_labelMouseEntered

    private void Again_buttonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Again_buttonMouseClicked
    {//GEN-HEADEREND:event_Again_buttonMouseClicked
        clip3.stop();
        IvysaurHitpoints_label.setText("" + 324);
        IvysaurHP_bar.setValue(100);
        CharmeleonHitpoints_label.setText("" + 324);
        CharmeleonHP_bar.setValue(100);
        clip.loop();
        Again_button.setVisible(false);
        BattleLog_txtarea.setText("");
        hide = true;
        show = true;
        IvyShowButtons();
        CharShowButtons();
    }//GEN-LAST:event_Again_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BattleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BattleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BattleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BattleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BattleUI().setVisible(true);
            }
        });
    }
    
    public void HideArrows()
    {
        if(hide == true)
        {
        Ivysaur_arrow1.setVisible(false);
        Ivysaur_arrow2.setVisible(false);
        Ivysaur_arrow3.setVisible(false);
        Ivysaur_arrow4.setVisible(false);
        Charmeleon_arrow1.setVisible(false);
        Charmeleon_arrow2.setVisible(false);
        Charmeleon_arrow3.setVisible(false);
        Charmeleon_arrow4.setVisible(false);
        }
        
    }
    
    public void IvyHideButtons()
    {
        if(hide == true)
        {
        Tackle_button.setVisible(false);
        VineWhip_button.setVisible(false);
        RazorLeaf_button.setVisible(false);
        SolarBeam_button.setVisible(false);
        IvyItems_button.setVisible(false);
        }
    }
    
    public void IvyShowButtons()
    {
        if(show == true)
        {
        Tackle_button.setVisible(true);
        VineWhip_button.setVisible(true);
        RazorLeaf_button.setVisible(true);
        SolarBeam_button.setVisible(true);
        IvyItems_button.setVisible(true);
        }
    }
    
    public void CharHideButtons()
    {
        if(hide == true)
        {
        Firespin_button.setVisible(false);
        Flamethrower_button.setVisible(false);
        Slash_button.setVisible(false);
        Ember_button.setVisible(false);
        CharItems_button.setVisible(false);
        }
    }
    
    public void CharShowButtons()
    {
        if(show == true)
        {
        Firespin_button.setVisible(true);
        Flamethrower_button.setVisible(true);
        Slash_button.setVisible(true);
        Ember_button.setVisible(true);
        CharItems_button.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Again_button;
    private javax.swing.JTextArea BattleLog_txtarea;
    private javax.swing.JLabel CharItems_button;
    private javax.swing.JLabel CharPotions_label;
    private javax.swing.JPanel Char_items_panel;
    private javax.swing.JLabel Char_potion_number;
    private javax.swing.JProgressBar CharmeleonHP_bar;
    private javax.swing.JLabel CharmeleonHP_label;
    private javax.swing.JPanel CharmeleonHP_panel;
    private javax.swing.JLabel CharmeleonHitpoints_label;
    private javax.swing.JLabel CharmeleonImage_label;
    private javax.swing.JLabel CharmeleonLvl_label;
    private javax.swing.JLabel CharmeleonSlash_label;
    private javax.swing.JLabel Charmeleon_arrow1;
    private javax.swing.JLabel Charmeleon_arrow2;
    private javax.swing.JLabel Charmeleon_arrow3;
    private javax.swing.JLabel Charmeleon_arrow4;
    private javax.swing.JLabel Charmeleon_label;
    private javax.swing.JLabel Ember_button;
    private javax.swing.JLabel Firespin_button;
    private javax.swing.JLabel Flamethrower_button;
    private javax.swing.JLabel IvyItems_button;
    private javax.swing.JLabel IvyPotions_label;
    private javax.swing.JPanel Ivy_items_panel;
    private javax.swing.JLabel Ivy_potion_number;
    private javax.swing.JProgressBar IvysaurHP_bar;
    private javax.swing.JLabel IvysaurHP_label;
    private javax.swing.JLabel IvysaurHitpoints_label;
    private javax.swing.JPanel IvysaurHp_panel;
    private javax.swing.JLabel IvysaurImage_label;
    private javax.swing.JLabel IvysaurLvl_label;
    private javax.swing.JLabel IvysaurSlash_label;
    private javax.swing.JLabel Ivysaur_arrow1;
    private javax.swing.JLabel Ivysaur_arrow2;
    private javax.swing.JLabel Ivysaur_arrow3;
    private javax.swing.JLabel Ivysaur_arrow4;
    private javax.swing.JLabel Ivysaur_label;
    private javax.swing.JLabel RazorLeaf_button;
    private javax.swing.JLabel Slash_button;
    private javax.swing.JLabel SolarBeam_button;
    private javax.swing.JLabel Tackle_button;
    private javax.swing.JLabel VineWhip_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
